pipelines:
  - name: build_maven_dep_tree_snapshot
    configuration:
      runtime:
        type: image
        image:
          auto:
            language: java
            versions:
              - "11"
    steps:
      - name: Snapshot
        type: Bash
        configuration:
          inputResources:
            - name: mavenDepTreeSnapshotGit
          integrations:
            - name: ecosys_entplus_deployer
        execution:
          onExecute:
            - cd $res_mavenDepTreeSnapshotGit_resourcePath

            # Set env
            - export CI=true
            - export JFROG_BUILD_STATUS=PASS
            - export JFROG_CLI_BUILD_NAME=ecosystem-maven-dep-tree-dev
            - export JFROG_CLI_BUILD_NUMBER=$run_number
            - export JFROG_CLI_BUILD_PROJECT=ecosys

            # Configure JFrog CLI
            - curl -fL https://install-cli.jfrog.io | sh
            - jf c rm --quiet
            - jf c add internal --url=$int_ecosys_entplus_deployer_url --user=$int_ecosys_entplus_deployer_user --password=$int_ecosys_entplus_deployer_apikey
            - jf mvnc --repo-resolve-releases ecosys-maven-remote --repo-resolve-snapshots ecosys-maven-remote --repo-deploy-releases ecosys-oss-release-local --repo-deploy-snapshots ecosys-oss-snapshot-local

            # Run audit
            - jf audit --fail=false

            # Delete former snapshots to make sure the release bundle will not contain the same artifacts
            - jf rt del "ecosys-oss-snapshot-local/com/jfrog/maven-dep-tree/*" --quiet

            # Build and publish snapshot
            - >
              env -i PATH=$PATH HOME=$HOME
              JFROG_CLI_BUILD_NAME=$JFROG_CLI_BUILD_NAME
              JFROG_CLI_BUILD_NUMBER=$JFROG_CLI_BUILD_NUMBER
              JFROG_CLI_BUILD_PROJECT=$JFROG_CLI_BUILD_PROJECT
              jf mvn clean deploy -B
            - jf rt bag && jf rt bce
            - jf rt bp

            # Distribute release bundle
            - jf ds rbc ecosystem-maven-dep-tree-snapshot $run_number --spec=./.jfrog-pipelines/release/specs/dev-rbc-filespec.json --sign
            - jf ds rbd ecosystem-maven-dep-tree-snapshot $run_number --site="releases.jfrog.io" --sync

